spring.application.name=demo

# Puerto del servidor
server.port=8080

# =========================================================
# CONFIGURACIÓN PARA SOPORTAR MÚLTIPLES SOLICITUDES CONCURRENTES
# =========================================================
# Número máximo de hilos de trabajo (peticiones simultáneas que se pueden procesar)
server.tomcat.threads.max=200
# Número mínimo de hilos de trabajo que siempre estarán disponibles
server.tomcat.threads.min-spare=10
# Número máximo de conexiones que el servidor aceptará y procesará
server.tomcat.max-connections=10000
# Número máximo de solicitudes que se pueden poner en cola cuando todos los hilos están ocupados
server.tomcat.accept-count=100
